api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  #api:
    address: ":3010"
  https:
    address: ":443"
    http:
      tls: {}
 
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
 
  file:
    directory: "/etc/traefik/config"
    watch: true

#certificatesResolvers:
#  letsencrypt:
#    acme:
#      email: amaury.cormier@gmail.com
#      storage: /letsencrypt/acme.json
#      httpChallenge:
#        entryPoint: http

accessLog: {}
log:
  level: debug