api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  nest:
    address: ":3010"
  websecure:
    address: ":443"
    http:
        tls: 
        certResolver: letsencrypt
    
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
 
  file:
    directory: "/etc/traefik/config"
    watch: true
  
  certResolver:
    letsencrypt:
      acme:
        email: inter@amap44.org
        storage: acme.json
        caServer: https://acme-staging-v02.api.letsencrypt.org/directory
        httpChallenge:
          # used during the challenge
          entryPoint: web


     


accessLog:
  #level: debug
  filePath: "/var/log/traefik/traefik.log"