api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  
  nest:
    address: ":3010"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: ":443"
    http:
      tls: {}
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    
  file:
    directory: "/etc/traefik/config"
    watch: true
  
#certificatesResolvers:
#  le:
#    acme:
#      email: admin@camap.tld
#      storage: /etc/traefik/ssl/acme.json
#      httpChallenge:
#        # used during the challenge
#        entryPoint: web

accessLog:
#  level: debug
  filePath: "/var/log/traefik/traefik.log"