api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  nest:
    address: ":3010"
  websecure:
    address: ":443"
    http:
      tls: 
      certResolver: le
    
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    
  file:
    directory: "/etc/traefik/config"
    watch: true
  
certificatesResolvers:
  le:
    acme:
      email: inter@amap44.org
      storage: /ssl/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

     


accessLog:
  filePath: "/var/log/traefik/traefik.log"