api:
  dashboard: true

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
  api:
    address: ":3010"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: amaury.cormier@gmail.com
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: http