api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  nest:
    address: ":3010"
  websecure:
    address: ":443"
    
    
  
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: true
    certificatesResolvers:
      myresolver:
        acme:
          email: your-email@example.com
          storage: acme.json
          httpChallenge:
            # used during the challenge
            entryPoint: web
  file:
    directory: "/etc/traefik/config"
    watch: true
  
certificatesResolvers:
  myresolver:
    acme:
      email: your-email@example.com
      storage: acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: web

     


accessLog:
  #level: debug
  filePath: "/var/log/traefik/traefik.log"